-- MIAYAAR PostgreSQL/Supabase baseline.  The quoted identifiers deliberately
-- preserve existing field names, avoiding an unaudited mapping change.
CREATE TYPE user_role AS ENUM ('user', 'admin');
CREATE TYPE methodology_status AS ENUM ('draft', 'testing', 'review', 'approved', 'production');
CREATE TYPE valuation_request_status AS ENUM ('received', 'completed', 'partial', 'rejected', 'failed');
CREATE TYPE valuation_audit_stage AS ENUM ('validation', 'data', 'gis', 'rules', 'valuation', 'confidence', 'reporting');
CREATE TYPE property_type AS ENUM ('apartment', 'villa', 'townhouse', 'office', 'retail', 'land', 'warehouse');
CREATE TYPE evidence_status AS ENUM ('eligible', 'rejected');
CREATE TYPE dld_import_status AS ENUM ('running', 'completed', 'failed');
CREATE TYPE dld_import_issue_type AS ENUM ('duplicate', 'rejected', 'invalid');

CREATE TABLE users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "openId" varchar(64) NOT NULL UNIQUE,
  name text,
  email varchar(320),
  "loginMethod" varchar(64),
  role user_role NOT NULL DEFAULT 'user',
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now(),
  "lastSignedIn" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE "methodologyVersions" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version varchar(32) NOT NULL UNIQUE,
  status methodology_status NOT NULL DEFAULT 'draft',
  "documentId" varchar(64) NOT NULL,
  checksum varchar(128) NOT NULL,
  configuration jsonb NOT NULL,
  "changeSummary" text NOT NULL,
  "approvedBy" varchar(64),
  "approvedAt" timestamptz,
  "createdAt" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE "valuationRequests" (
  id varchar(64) PRIMARY KEY,
  "userId" integer,
  "methodologyVersion" varchar(32) NOT NULL,
  "propertyInput" jsonb NOT NULL,
  status valuation_request_status NOT NULL DEFAULT 'received',
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "completedAt" timestamptz
);

CREATE TABLE "valuationAuditEvents" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "valuationRequestId" varchar(64) NOT NULL,
  stage valuation_audit_stage NOT NULL,
  "eventType" varchar(64) NOT NULL,
  payload jsonb NOT NULL,
  "createdAt" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE "marketTransactions" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sourceTransactionId" varchar(128) NOT NULL UNIQUE,
  source varchar(64) NOT NULL DEFAULT 'DLD',
  "sourceChecksum" varchar(128) NOT NULL,
  "transactionDate" timestamptz NOT NULL,
  district varchar(160) NOT NULL,
  "propertyType" property_type NOT NULL,
  "rawType" varchar(160) NOT NULL,
  "rawSubType" varchar(160),
  "areaSqm" double precision NOT NULL,
  "salePriceAed" double precision NOT NULL,
  "pricePerSqm" double precision NOT NULL,
  "evidenceStatus" evidence_status NOT NULL DEFAULT 'eligible',
  "rejectionReason" varchar(255),
  "ingestedAt" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX "marketTransactions_district_type_date_idx" ON "marketTransactions" (district, "propertyType", "transactionDate");
CREATE INDEX "marketTransactions_type_date_idx" ON "marketTransactions" ("propertyType", "transactionDate");

CREATE TABLE "dldImportRuns" (
  id varchar(64) PRIMARY KEY,
  "sourceLabel" varchar(255) NOT NULL,
  "sourceChecksum" varchar(128) NOT NULL,
  "recordsRead" integer NOT NULL,
  "normalizedRecords" integer NOT NULL,
  "uniqueTransactionIds" integer NOT NULL,
  "duplicateTransactionIds" integer NOT NULL,
  "eligibleRecords" integer NOT NULL,
  "rejectedRecords" integer NOT NULL,
  "skippedRecords" integer NOT NULL,
  status dld_import_status NOT NULL,
  "startedAt" timestamptz NOT NULL DEFAULT now(),
  "completedAt" timestamptz
);
CREATE INDEX "dldImportRuns_source_checksum_idx" ON "dldImportRuns" ("sourceChecksum");

CREATE TABLE "dldImportIssues" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "importRunId" varchar(64) NOT NULL,
  "recordIndex" integer NOT NULL,
  "issueType" dld_import_issue_type NOT NULL,
  reason varchar(255) NOT NULL,
  "sourceTransactionId" varchar(128),
  "recordFingerprint" varchar(128) NOT NULL,
  "createdAt" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX "dldImportIssues_run_type_idx" ON "dldImportIssues" ("importRunId", "issueType");

CREATE TABLE "valuationRateLimitWindows" (
  id varchar(128) PRIMARY KEY,
  "windowStart" timestamptz NOT NULL,
  "requestCount" integer NOT NULL,
  "expiresAt" timestamptz NOT NULL,
  "updatedAt" timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX "valuationRateLimitWindows_expires_idx" ON "valuationRateLimitWindows" ("expiresAt");
